spring.application.name=admin
server.servlet.context-path=/ecommerce-admin

# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true
spring.datasource.username=flexitech
spring.datasource.password=o;Ry)0=u>Ncc+pS#
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
spring.jpa.hibernate.ddl-auto=update

# Thymeleaf Cache Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML


# Logging levels
logging.level.org.flexitech.projects.erp=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate=WARN

# Log file
logging.file.name=/home/tomcat/ecommerce/logs/admin/admin.log

# Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

#image path
image.path=/home/tomcat/ecommerce/images
image.context.path=/ecommerce-images/
image.zip.upload.path=/home/tomcat/ecommerce/images/upload

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

file.export.path=/home/tomcat/ecommerce/export/error-reports

#url
app.url=https://flexitech.publicvm.com/ecommerce/
app.admin.url=https://flexitech.publicvm.com/ecommerce-admin/
app.api.url=https://flexitech.publicvm.com/ecommerce-api/

#messages
spring.messages.basename=messages
spring.messages.encoding=UTF-8

#messaging
spring.security.messaging.csrf.enabled=false

#mail sender
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=itech.saizawmyint@gmail.com
spring.mail.password=bnqewkgydfwlruep
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true