spring.main.allow-bean-definition-overriding=true
spring.profiles.active=dev

spring.devtools.restart.enabled=true
spring.devtools.livereload.enabled=true

spring.messages.basename=messages
spring.messages.encoding=UTF-8
server.servlet.session.timeout=120m