SET SQL_SAFE_UPDATES = 0;

UPDATE menus SET name_mm = 'ဒက်ရှ်ဘုတ်' WHERE code = 'DASHBOARD';
UPDATE menus SET name_mm = 'အသုံးပြုသူ စီမံခန့်ခွဲမှု' WHERE code = 'USER_CONTROL';
UPDATE menus SET name_mm = 'အသုံးပြုသူများ' WHERE code = 'USER_LIST';
UPDATE menus SET name_mm = 'Role များ' WHERE code = 'ROLE_LIST';
UPDATE menus SET name_mm = 'ဆက်တင်များ' WHERE code = 'SETTINGS';
UPDATE menus SET name_mm = 'မီနူး အသုံးပြုခွင့်' WHERE code = 'USER_MANAGEMENT_MENU_ACCESS_MANAGE';
UPDATE menus SET name_mm = 'ဖောက်သည်' WHERE code = 'CUSTOMER_MANAGEMENT';
UPDATE menus SET name_mm = 'ဖောက်သည်များ' WHERE code = 'CUSTOMER_LIST';
UPDATE menus SET name_mm = 'လိုင်စင်' WHERE code = 'LICENSE_MANAGEMENT';
UPDATE menus SET name_mm = 'ထုတ်ကုန်များ' WHERE code = 'PRODUCT_LIST';
UPDATE menus SET name_mm = 'ထုတ်ကုန် လုပ်ဆောင်ချက်များ' WHERE code = 'PRODUCT_FEATURE_LIST';
UPDATE menus SET name_mm = 'လိုင်စင် အစီအစဉ်များ' WHERE code = 'LICENSE_PLAN_LIST';
UPDATE menus SET name_mm = 'လိုင်စင်များ' WHERE code = 'LICENSE_LIST';
UPDATE menus SET name_mm = 'ထုတ်ကုန်' WHERE code = 'PRODUCT_MANAGEMENT';
UPDATE menus SET name_mm = 'အစီရင်ခံစာများ' WHERE code = 'REPORTS_MANAGEMENT';
UPDATE menus SET name_mm = 'ဖောက်သည် ဝယ်ယူမှု အစီရင်ခံစာ' WHERE code = 'CUSTOMER_PURCHASE_REPORT';
UPDATE menus SET name_mm = 'ကုန်ပစ္စည်း စာရင်း' WHERE code = 'INV_MGMT';
UPDATE menus SET name_mm = 'ပစ္စည်းများ စီမံခြင်း' WHERE code = 'INV_ITEM';
UPDATE menus SET name_mm = 'ပစ္စည်း အမျိုးအစားများ' WHERE code = 'INV_CATEGORY';
UPDATE menus SET name_mm = 'Brand များ' WHERE code = 'INV_BRAND';
UPDATE menus SET name_mm = 'ယူနစ်များ' WHERE code = 'INV_UOM';
UPDATE menus SET name_mm = 'ဂိုဒေါင် စီမံခြင်း' WHERE code = 'INV_WAREHOUSE';
UPDATE menus SET name_mm = 'ဂိုဒေါင်ထဲက နေရာများ' WHERE code = 'INV_LOCATION';
UPDATE menus SET name_mm = 'ပစ္စည်းပေးသွင်းသူများ' WHERE code = 'INV_SUPPLIER';
UPDATE menus SET name_mm = 'စတော့ စာရွက်စာတမ်းများ' WHERE code = 'INV_STOCK_DOCS';
UPDATE menus SET name_mm = 'ပစ္စည်း လက်ခံမှတ်တမ်း' WHERE code = 'INV_GOODS_RECEIPT';
UPDATE menus SET name_mm = 'ပစ္စည်း ထုတ်ပေးမှတ်တမ်း' WHERE code = 'INV_GOODS_ISSUE';
UPDATE menus SET name_mm = 'စတော့ ချိန်ညှိခြင်း' WHERE code = 'INV_STOCK_ADJUSTMENT';
UPDATE menus SET name_mm = 'စတော့ အစီရင်ခံစာများ' WHERE code = 'INV_STOCK_REPORT';
UPDATE menus SET name_mm = 'လက်ကျန်စတော့' WHERE code = 'INV_STOCK_ON_HAND';
UPDATE menus SET name_mm = 'စတော့ ကတ်' WHERE code = 'INV_STOCK_CARD';